name: yolov5
channels:
  - hcc
  - https://conda.anaconda.org/t/HC-83c774c8-94fe-4b2f-b0b2-22cd71073412/hcc
  - conda-forge
  - bioconda
  - defaults
  - file:///util/opt/conda_repo
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3
  - aom=3.3.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - colorama=0.4.4
  - conda=4.12.0
  - conda-package-handling=1.8.1
  - cryptography=36.0.1
  - cudatoolkit=11.2.2
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.7
  - ffmpeg=5.0.0
  - fontconfig=2.13.96
  - fonttools=4.30.0
  - freetype=2.10.4
  - frozenlist=1.3.0
  - future=0.18.2
  - gast=0.4.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.39.1
  - grpcio=1.39.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - ipykernel=6.9.2
  - ipython=8.1.1
  - jbig=2.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libdrm=2.4.109
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libiconv=1.16
  - libimagequant=2.15.1
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libsolv=0.7.22
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libva=2.14.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - lzo=2.10
  - magma=2.5.4
  - mamba=0.15.3
  - markdown=3.3.6
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - nccl=2.12.7.1
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.6
  - ninja=1.10.2
  - nspr=4.32
  - nss=3.74
  - numpy=1.19.5
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - pandas=1.4.1
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.27
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - qt=5.12.9
  - re2=2021.09.01
  - readline=8.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - ruamel_yaml=0.15.100
  - scikit-learn=1.0.2
  - scikit-plot=0.3.7
  - scipy=1.8.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=60.9.3
  - six=1.15.0
  - sleef=3.5.1
  - snappy=1.1.8
  - sqlite=3.38.5
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - svt-av1=0.9.1
  - tbb=2021.5.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.6.0
  - termcolor=1.1.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchvision=0.11.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wrapt=1.12.1
  - x264=1!161.3030
  - x265=1.9
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - alabaster==0.7.12
    - babel==2.10.1
    - cachecontrol==0.12.11
    - cachy==0.3.0
    - cleo==0.8.1
    - clikit==0.6.2
    - cramjam==2.5.0
    - crashtest==0.3.1
    - distlib==0.3.4
    - dnspython==2.2.1
    - docker-pycreds==0.4.0
    - docutils==0.17.1
    - fastparquet==0.8.1
    - filelock==3.7.0
    - fsspec==2022.5.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - html5lib==1.1
    - imageio==2.19.2
    - imagesize==1.3.0
    - imgaug==0.4.0
    - jeepney==0.8.0
    - jinja2==3.1.2
    - jsonschema==4.5.1
    - keyring==23.5.1
    - lockfile==0.12.2
    - loguru==0.6.0
    - markupsafe==2.1.1
    - minio==7.1.8
    - msgpack==1.0.3
    - networkx==2.8.2
    - nvidia-ml-py3==7.352.0
    - opencv-python==4.5.5.64
    - packaging==20.9
    - pastel==0.2.1
    - pathtools==0.1.2
    - pillow==9.1.1
    - pip==22.1.2
    - pkginfo==1.8.2
    - platformdirs==2.5.2
    - poetry==1.1.13
    - poetry-core==1.0.8
    - promise==2.3
    - protobuf==3.20.0
    - pyarrow==7.0.0
    - pybboxes==0.0.2
    - pylev==1.4.0
    - pymongo==4.1.1
    - pyrsistent==0.18.1
    - python-color-transfer==0.1.0
    - python-dotenv==0.20.0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - ray==1.12.1
    - requests-toolbelt==0.9.1
    - schedule==1.1.0
    - scikit-image==0.19.2
    - secretstorage==3.3.2
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shapely==1.8.2
    - shellingham==1.4.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - sphinx==5.0.1
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tifffile==2022.5.4
    - tomlkit==0.11.0
    - torch==1.10.0
    - virtualenv==20.14.1
    - wandb==0.12.16
    - webencodings==0.5.1
    - zstandard==0.17.0
