name: yolov5
channels:
  - pytorch
  - hcc
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.3.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.3.18
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - colorama=0.4.4
  - conda=4.12.0
  - conda-package-handling=1.8.0
  - cryptography=36.0.0
  - cudatoolkit=10.2.89
  - curl=7.82.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.7
  - ffmpeg=5.0.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - git=2.35.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=69.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.2
  - ipython=8.1.1
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libarchive=3.5.2
  - libcurl=7.82.0
  - libdeflate=1.10
  - libdrm=2.4.109
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libmamba=0.22.1
  - libmambapy=0.22.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libpciaccess=0.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libsolv=0.7.20
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.18.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.43.0
  - libva=2.14.0
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.22.1
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.7.3
  - numpy-base=1.21.2
  - openh264=2.1.1
  - openssl=1.1.1n
  - parso=0.8.3
  - pcre2=10.37
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.4
  - prompt-toolkit=3.0.27
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyzmq=22.3.0
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - setuptools=61.1.1
  - six=1.16.0
  - sqlite=3.38.0
  - stack_data=0.2.0
  - svt-av1=0.9.1
  - tk=8.6.12
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - tqdm=4.63.1
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yaml-cpp=0.6.3
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - cachetools==5.0.0
    - click==8.0.4
    - cycler==0.11.0
    - deprecated==1.2.13
    - docker-pycreds==0.4.0
    - filelock==3.6.0
    - fonttools==4.31.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - jsonschema==4.4.0
    - kiwisolver==1.4.0
    - loguru==0.6.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - msgpack==1.0.3
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pandas==1.4.1
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dotenv==0.20.0
    - pytz==2022.1
    - pyyaml==6.0
    - ray==1.11.0
    - redis==4.2.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.0
    - seaborn==0.11.2
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - smmap==5.0.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - thop==0.0.31-2005241907
    - wandb==0.12.11
    - werkzeug==2.0.3
    - wrapt==1.14.0
    - yaspin==2.1.0
    - zipp==3.7.0
