name: torch-gpu
channels:
  - conda-forge
  - defaults
  - hcc
  - https://conda.anaconda.org/t/HC-83c774c8-94fe-4b2f-b0b2-22cd71073412/hcc
  - bioconda
  - file:///util/opt/conda_repo
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - abseil-cpp=20200923.3
  - absl-py=0.10.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.7
  - click=8.0.3
  - cryptography=35.0.0
  - cudatoolkit=11.2.2
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - entrypoints=0.3
  - flatbuffers=2.0.0
  - freetype=2.10.4
  - frozenlist=1.2.0
  - future=0.18.2
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.34.1
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=64.2
  - idna=2.10
  - importlib-metadata=4.8.2
  - ipykernel=6.5.0
  - ipython=7.29.0
  - jbig=2.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9d
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libimagequant=2.15.1
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - magma=2.5.4
  - markdown=3.3.6
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - multidict=5.2.0
  - nccl=2.11.4.1
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - numpy=1.19.5
  - oauthlib=3.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - pandas=1.3.4
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.3.1
  - prompt-toolkit=3.0.22
  - protobuf=3.16.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytorch=1.9.0
  - pytorch-gpu=1.9.0
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - readline=8.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.1
  - scikit-plot=0.3.7
  - scipy=1.7.2
  - setuptools=59.2.0
  - six=1.15.0
  - sleef=3.5.1
  - snappy=1.1.8
  - sqlite=3.36.0
  - tbb=2021.4.0
  - tensorboard=2.5.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.5.0
  - tensorflow-base=2.5.0
  - tensorflow-estimator=2.5.0
  - tensorflow-gpu=2.5.0
  - termcolor=1.1.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - torchvision=0.10.0
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - werkzeug=2.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - distlib==0.3.4
    - dnspython==2.2.1
    - docker-pycreds==0.4.0
    - filelock==3.7.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - jsonschema==4.5.1
    - loguru==0.6.0
    - minio==7.1.8
    - msgpack==1.0.3
    - nvidia-ml-py3==7.352.0
    - opencv-python==4.5.5.64
    - pathtools==0.1.2
    - platformdirs==2.5.2
    - promise==2.3
    - psutil==5.9.0
    - pymongo==4.1.1
    - pyrsistent==0.18.1
    - python-dotenv==0.20.0
    - pyyaml==6.0
    - ray==1.12.1
    - requests==2.27.1
    - schedule==1.1.0
    - seaborn==0.11.2
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - smmap==5.0.0
    - tqdm==4.64.0
    - virtualenv==20.14.1
    - wandb==0.12.16
    - zstandard==0.17.0
