name: Docker Build

on:   
  push:
  pull_request:

env:
  IMAGE_NAME: birdfsd-yolov5

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Compute Short SHA 
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: |
          echo "Build: ${SHORT_SHA}"
          docker build . --file Dockerfile \
            --tag "${IMAGE_NAME}:${SHORT_SHA}" \
            --label "runnumber=${GITHUB_RUN_ID}"
