name: JSON to YOLOv5 (data preprocessing)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run json2yolov5.py
      env: 
        TOKEN: ${{ secrets.TOKEN }}
        LS_HOST: ${{ secrets.LS_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        EXCLUDE_LABELS: ${{ secrets.EXCLUDE_LABELS }}
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        S3_REGION: ${{ secrets.S3_REGION }}
      run: |
        python json2yolov5.py --only-tar-file --enable-s3 --filter-cls-with-instances-under 20

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          tasks.json
          classes.json
          dataset-YOLO*.tar
        retention-days: 90
