name: Predict

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run sync_tasks.py
      env: 
        PROJECTS_ID: ${{ secrets.PROJECTS_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        LS_HOST: ${{ secrets.LS_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        EXCLUDE_LABELS: ${{ secrets.EXCLUDE_LABELS }}
        MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        MINIO_REGION: ${{ secrets.MINIO_REGION }}
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      run: |
        python auto_prediction_schedule.py --once
